In [1]:
import cv2
import numpy as np

In [4]:
img = cv2.imread('img_4.jpg') # Read image
re_img = cv2.resize(img, (500, 500)) # Resize image to 500x500
cv2.imshow('Actor Image', re_img) # Show image in a window
cv2.waitKey(0) # Wait for a key press to close the window. time -> ms
cv2.destroyAllWindows() # Close all OpenCV windows

In [9]:
v = np.array([1,2,3,1,2,3])
np.hstack((v,v))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
img = cv2.imread('img_2.jpg') # Read image
print(img) # RGB

[[[141  73  44]
  [141  73  44]
  [141  73  44]
  ...
  [ 74  60  66]
  [ 73  59  65]
  [ 73  59  65]]

 [[141  73  44]
  [141  73  44]
  [140  72  43]
  ...
  [ 76  62  68]
  [ 75  61  67]
  [ 75  61  67]]

 [[140  72  43]
  [140  72  43]
  [140  72  43]
  ...
  [ 78  64  70]
  [ 77  63  69]
  [ 76  62  68]]

 ...

 [[191 162 158]
  [197 168 164]
  [202 172 167]
  ...
  [177 167 173]
  [177 167 173]
  [177 167 173]]

 [[191 162 158]
  [204 175 171]
  [202 172 167]
  ...
  [179 169 175]
  [179 169 175]
  [179 169 175]]

 [[201 172 168]
  [206 177 173]
  [188 158 153]
  ...
  [180 170 176]
  [180 170 176]
  [180 170 176]]]


In [ ]:
# horisontal stacking image
img = cv2.imread('img_4.jpg') # Read image
re_img = cv2.resize(img, (300, 300)) # Resize image to 500x500

h = np.hstack((re_img, re_img)) # Horizontal stacking

cv2.imshow('Actor Image', h) # Show image in a window
cv2.waitKey(0) # Wait for a key press to close the window. time -> ms
cv2.destroyAllWindows() # Close all OpenCV windows

In [16]:
# vertical stacking image
img = cv2.imread('img_4.jpg') # Read image
re_img = cv2.resize(img, (300, 300)) # Resize image to 500x500

v = np.vstack((re_img, re_img, re_img, re_img)) # Vertical stacking

cv2.imshow('Actor Image', v) # Show image in a window
cv2.waitKey(0) # Wait for a key press to close the window. time -> ms
cv2.destroyAllWindows() # Close all OpenCV windows

combinin both horizontally and vertically

In [19]:
img = cv2.imread('img_2.jpg') # Read image
re_img = cv2.resize(img, (300, 400)) # Resize image to 200x200
h = np.hstack((re_img, re_img, re_img)) # Horizontal stacking
v = np.vstack((h, h)) # Vertical stacking
cv2.imshow('Actor Image', v) # Show image in a window
cv2.waitKey(0) # Wait for a key press to close the window. time -> ms
cv2.destroyAllWindows() # Close all OpenCV windows