In [2]:
import numpy as np

Basic array creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4,5,"hello"]
a

[1, 2, 3, 4, 5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Genration Fucnion

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#linear space
arr = np.linspace(0,10,5)
arr 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random Genration Function

In [12]:
np.random.rand(5,3) #this is normalization 0 to 1

array([[0.06006368, 0.32531681, 0.66202961],
       [0.49633495, 0.17263804, 0.43458989],
       [0.2290667 , 0.59070688, 0.18144991],
       [0.16974318, 0.62091155, 0.05954788],
       [0.91757005, 0.05293905, 0.32421834]])

In [13]:
#this is standardization -3 to 3
np.random.randn(5,3)

array([[-1.29687051,  0.42595167, -0.73118493],
       [ 0.62327539,  0.99975944,  0.18687465],
       [-0.28937615,  0.55644572, -0.2561451 ],
       [-1.27295307,  0.50591085, -2.30152581],
       [-1.16042681, -1.663992  ,  1.37512241]])

In [14]:
np.random.randint(6)

0

In [15]:
np.random.randint(1,100,10)

array([14, 11, 22, 24, 48,  4, 87,  5,  4, 48], dtype=int32)

Array Attributes

In [16]:
arr = np.array([[1, 2, 3], [4,5,6], [7,8,9]]) 

In [17]:
#shape
arr.shape

(3, 3)

In [18]:
# size
arr.size

9

In [27]:
# data type
arr.dtype

dtype('int64')

Array Method

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.min()

np.int64(1)

In [21]:
arr.max()

np.int64(9)

In [22]:
arr.sum()

np.int64(45)

In [23]:
np.sum(arr, axis=0) #column wise sum

array([12, 15, 18])

In [24]:
np.sum(arr, axis= 1) #row wise sum

array([ 6, 15, 24])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.std() #standard deviation

np.float64(2.581988897471611)

In [28]:
arr.argmax() #index of max value

np.int64(8)

In [29]:
arr.argmin() #index of min value

np.int64(0)

Reshaping and Resizing

In [30]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
#resize
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])