In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [5]:
arr[9]

np.int64(20)

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [10]:
arr[:3] #  default 0 to 3

array([11, 12, 13])

In [11]:
arr[:] # default 0 to end

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr_slice = arr[3::2] # from index 3 to end with step size 2
arr_slice

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING

In [17]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[2] # 2nd row

array([11, 12, 13, 14, 15])

In [ ]:
arr[5][3] # element at 5th row and 3rd column

np.int64(29)

In [20]:
arr[0,0]

np.int64(1)

In [21]:
arr[0][0]

np.int64(1)

In [24]:
slice = arr[0:2, 1:3] # rows 0 and 1, columns 1 and 2
slice

array([[2, 3],
       [7, 8]])

In [25]:
arr[3:6, 3:5] # rows 3 to 5, columns 3 to 4

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
arr[3:, 2:] # rows 3 to end, columns 2 to end

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [27]:
arr[:3] #first three elements

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[:,2] #  2nd column

array([ 3,  8, 13, 18, 23, 28])

Boolean indexing

In [33]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])