ARRAY OPERATION

Arithmatic operation

In [2]:
import numpy as np

In [ ]:
a1 = np.array([1, 2, 3, 4, 5]) # the size should be same
a2 = np.array([6, 7, 8, 9, 10])
print("Array 1:", a1)
print("Array 2:", a2)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


In [12]:
a1 + a2  # Addition


array([ 7,  9, 11, 13, 15])

In [13]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [14]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [15]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
a1 // a2  # Floor Division

array([0, 0, 0, 0, 0])

In [17]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

BRODCASTING

In [18]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [19]:
arr+10 

array([20, 30, 40, 50])

In [21]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr2 + 10 # add 10 to each element

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [24]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

DEEP AND SHALLOW COPY

In [27]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [31]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [32]:
a 
b = a

In [33]:
b[0] = 100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [34]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [35]:
c = a.copy() # deep copy
c[0] = 500
c

array([500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
a # original array is not changed

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

Matrix Operation

In [45]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
B

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
A * B # element-wise multiplication
# but not matrix multiplication

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [49]:
A @ B # matrix multiplication

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [50]:
np.dot(A, B)  # another way to do matrix multiplication

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [51]:
A.T # transpose of matrix A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])