ADVANCE ARRAY MANIPULATION

Stacking Array

In [6]:
import numpy as np

In [10]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[10,11]])
A

array([[1, 2],
       [4, 5]])

In [11]:
B

array([[ 7,  8],
       [10, 11]])

In [13]:
#stacking array
np.vstack((A,B)) # vertical stacking

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [14]:
np.hstack((A,B)) # horizontal stacking

array([[ 1,  2,  7,  8],
       [ 4,  5, 10, 11]])

In [15]:
np.column_stack((A,B)) # column wise stacking

array([[ 1,  2,  7,  8],
       [ 4,  5, 10, 11]])

Spliting array

In [19]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2) # horizontal splitting
# we can't split if the number of columns is odd

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
np.vsplit(c,2) # vertical splitting

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [28]:
a = np.vsplit(c,4) # vertical splitting into 4 parts
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
np.hsplit(c,4) # horizontal splitting into 4 parts  


[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [29]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
