GENRAL QUESTION

In [41]:
#valid sudoku
import numpy as np

In [42]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [43]:
b = np.sum(s, axis = 1)
#b == 45
for i in b:
    if i != 45:
        print("invalid sudoku")
        break
else:
    print("for row it it is valid")

for row it it is valid


In [44]:
c = np.sum(s, axis = 0)
#b == 45
for i in b:
    if i != 45:
        print("invalid sudoku")
        break
else:
    print("for columns it it is valid")

for columns it it is valid


In [45]:
s[0:3, 0:3] # first 3x3 matrix

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [46]:
s[0:3, 3:6] # second 3x3 matrix

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [47]:
s[0:3, 6:9] # third 3x3 matrix

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [48]:
for i in range(0,9,3):
    for j in range(0,9,3):
        #print(s[i:i+3, j:j+3])
        n = s[i:i+3, j:j+3]
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


In [49]:
import numpy as np
# columns: [age, match marks, Science marks]
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

In [50]:
# Get the shape of the matrix
data.shape

(5, 3)

In [51]:
# find the average age of students
np.mean(data[:, 0])

np.float64(18.4)

In [52]:
# extract the math marks
data[:, 1]

array([85, 92, 76, 65, 90])

In [53]:
# find the heighst science marks
np.max(data[:, 2])

np.int64(95)

In [54]:
# Get details of students whose math marks is greater than 90
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [55]:
# increase the math marks by 5
data[:, 1] + 5

array([90, 97, 81, 70, 95])

In [56]:
# find how many students are youngers than 19
len(data[data[:, 0] < 19])

3

In [57]:
# Calculate the average marks in each subject(in column wise)
np.mean(data[:, 1:], axis=0)

array([81.6, 83.2])

In [58]:
# Get data of students who socred at least 80 in both subjects
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [59]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [60]:
# Replace all Science marks less than 75 with 0
data[:,2][data[:, 2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])