In [1]:
import numpy as np

Basic array creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4,5,"hello"]
a

[1, 2, 3, 4, 5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Genration Fucnion

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#linear space
arr = np.linspace(0,10,5)
arr 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Random Genration Function

In [ ]:
np.random.rand(5,3) #this is normalization 0 to 1

array([[0.93155657, 0.92865169, 0.08455724],
       [0.95807949, 0.90676183, 0.09402916],
       [0.55016079, 0.36234062, 0.53496049],
       [0.35738427, 0.99874999, 0.15311144],
       [0.83524676, 0.49211862, 0.58362488]])

In [ ]:
#this is standardization -3 to 3
np.random.randn(5,3)

array([[ 0.73766448, -0.38467017,  0.1391635 ],
       [-0.23074531,  1.70095922,  0.9282717 ],
       [-1.22731493,  1.14537996,  1.21362831],
       [ 0.21077034, -1.0636582 , -0.72130912],
       [ 2.08108322,  1.31814805, -1.00078509]])

In [20]:
np.random.randint(6)

2

In [19]:
np.random.randint(1,100,10)

array([22, 70, 45, 50, 22, 36, 52, 38, 87, 91], dtype=int32)

Array Attributes

In [24]:
arr = np.array([[1, 2, 3], [4,5,6], [7,8,9]]) 

In [25]:
#shape
arr.shape

(3, 3)

In [26]:
# size
arr.size

9

In [27]:
# data type
arr.dtype

dtype('int64')

Array Method