In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('img_1.jpg')
img = cv2.resize(img, (600, 500))

print(img.shape)


(500, 600, 3)


In [3]:
print(img)

[[[ 54  49  44]
  [ 53  51  40]
  [ 53  53  41]
  ...
  [ 84  79  64]
  [ 86  80  69]
  [ 83  77  66]]

 [[ 49  53  41]
  [ 56  53  38]
  [ 52  52  40]
  ...
  [ 84  78  63]
  [ 84  78  67]
  [ 84  78  67]]

 [[ 51  53  41]
  [ 56  52  37]
  [ 53  51  40]
  ...
  [ 84  79  64]
  [ 82  79  60]
  [ 84  78  65]]

 ...

 [[ 28  14   8]
  [ 26  12   6]
  [ 26  11   8]
  ...
  [134 126 119]
  [136 128 115]
  [136 127 114]]

 [[ 27  12   9]
  [ 24   8   5]
  [ 23   8   5]
  ...
  [136 129 120]
  [133 127 114]
  [133 127 114]]

 [[ 26  11   8]
  [ 24   6  13]
  [ 24   9   6]
  ...
  [135 129 116]
  [133 127 114]
  [134 127 114]]]


In [5]:
new_img = np.ones((500, 600, 3), dtype=np.uint8) * 255
#print(new_img)

cv2.imshow('Blank Image', new_img)
cv2.imshow('Image', img)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
new_img = np.zeros((500, 600, 3), dtype=np.uint8) * 255
#print(new_img)

cv2.imshow('Blank Image', new_img)
cv2.imshow('Image', img)  
cv2.waitKey(0)
cv2.destroyAllWindows()